version: 2.0
workflows:
  python_build:
    name: Python Build
    environment:
      # Python is automatically set up in the default environment
      # You don't need to explicitly mention the image
      flutter: "latest"  # This line is optional, used for Flutter projects (not necessary for pure Python)
    scripts:
      - python3 soul.py  # Run your Python script with python3
