version: 2.0
workflows:
  python_build:
    name: Python Build
    environment:
      # Codemagic already provides Python by default
    scripts:
      - python3 -m pip install -r requirements.txt  # Install dependencies if needed
      - python3 soul.py  # Run the Python script with python3
