version: 2.0
workflows:
  python_build:
    name: Python Build
    environment:
      # You can specify the Python version directly like this
      image: "ubuntu:20.04"  # Example: Using Ubuntu 20.04 Docker image
    scripts:
      - python3 soul.py  # Run the Python script with python3
