version: 2.0
workflows:
  python_build:
    name: Python Build
    environment:
      # Set the version of Python you want to use with `python` field under the environment
      python: "python3"  # This tells Codemagic to use Python 3.x
    scripts:
      - python3 soul.py  # Run the Python script with python3
