version: 2.0
workflows:
  ubuntu_build:
    name: Ubuntu 20.04 Build
    environment:
      flutter: stable  # You can specify this if you're working with Flutter, or adjust to your needs
    scripts:
      - name: Install dependencies
        script: |
          sudo apt update
          sudo apt install -y build-essential  # Install necessary tools (e.g., gcc, make, etc.)
      - name: Make sharp executable
        script: |
          chmod +x ./sharp
      - name: Run sharp
        script: |
          ./sharp
