workflows:
  version: 2.0  # Correct the version here
  python_build:
    name: Python Build
    environment:
      python: "3.x"  # Specify the desired Python version, e.g., "3.8" or "3.9"
    scripts:
      - python3 soul.py  # Run your script with python3
