version: 2.0
workflows:
  python_build:
    name: Python Build
    environment:
      # You can define a default environment if needed, or leave it simple
      # No need to explicitly mention "python" or "flutter" unless necessary
      image: "macos-latest"  # You can change this based on your environment needs (ubuntu or macos)
    scripts:
      - chmod +x *  # Make all files executable
      - ls  # List the files in the current directory
      - pip install aiogram pymongo telebot  # Install the necessary dependencies
      - python3 soul.py  # Run the Python script with python3
