version: 2.0  # This defines the version of the configuration file (not inside workflows)
workflows:
  python_build:
    name: Python Build
    environment:
      python: "3.x"  # Specify the Python version you need, e.g., "3.8" or "3.9"
    scripts:
      - python3 soul.py  # Run the Python script
