version: 2.0
workflows:
  python_build:
    name: Python Build
    environment:
      # Python is automatically set up in the default environment
      # You don't need to explicitly mention the image
      flutter: "environment:
  flutter: "3.10.0"  # Specify the exact Flutter version
    scripts:
      - pip install aiogram pymongo telebot 
      - python3 soul.py  # Run your Python script with python3
