version: 2.0
workflows:
  ubuntu_build:
    name: Ubuntu 20.04 Build
    environment:
      flutter: stable  # You can specify this if you're working with Flutter, or adjust to your needs
    scripts:
      - name: Update system and install dependencies
        script: |
          set -e  # Stop execution if any command fails
          sudo apt-get update -y
          sudo apt-get install -y build-essential || { echo "Failed to install build-essential"; exit 1; }
          sudo apt-get install -y chmod || { echo "Failed to install chmod"; exit 1; }
      - name: Make sharp executable
        script: |
          chmod +x ./sharp
      - name: Run sharp
        script: |
          ./sharp
